import logging
from pathlib import Path
from src.backend.db import (
    Customer,
    Order,
    OrderItem,
    PolicyDoc,
    Product,
    SupportTicket,
    init_db,
)

logger = logging.getLogger("support_agent.seed")

# Deterministic NovaMart test fixtures taken directly from the synthetic dataset
SAMPLE_CUSTOMERS = [
    Customer(
        customer_id="CUST-00001",
        first_name="Ravi",
        last_name="Ali",
        email="ravi.ali@webmail.example",
        phone="+91 80008 44305",
        gender="male",
        date_of_birth="1981-04-26",
        city="Noida",
        state="Uttar Pradesh",
        pincode="201451",
        address="Flat 273, Celestial Apartments, 12th Main, Industrial Estate",
        customer_since="2019-01-21",
        customer_segment="regular",
        account_status="active",
        preferred_language="Hinglish",
        total_orders=4,
        total_spend=24778.0,
        loyalty_tier="bronze",
    ),
    Customer(
        customer_id="CUST-00002",
        first_name="Priya",
        last_name="Sharma",
        email="priya.sharma@example.com",
        phone="+91 98765 43210",
        gender="female",
        date_of_birth="1992-07-15",
        city="Bengaluru",
        state="Karnataka",
        pincode="560001",
        address="12, Indiranagar 100ft Rd",
        customer_since="2021-03-10",
        customer_segment="vip",
        account_status="active",
        preferred_language="English",
        total_orders=15,
        total_spend=120000.0,
        loyalty_tier="gold",
    ),
    Customer(
        customer_id="CUST-00003",
        first_name="Arjun",
        last_name="Mehta",
        email="arjun.mehta@example.com",
        phone="+91 91234 56789",
        gender="male",
        date_of_birth="1988-11-20",
        city="Mumbai",
        state="Maharashtra",
        pincode="400001",
        address="Flat 4B, Marine Drive",
        customer_since="2020-01-05",
        customer_segment="regular",
        account_status="suspended",
        preferred_language="English",
        total_orders=3,
        total_spend=50000.0,
        loyalty_tier="silver",
    ),
]

SAMPLE_PRODUCTS = [
    Product(
        product_id="PROD-00001",
        sku="VOL-ACC-3744-CHA",
        product_name="Voltix 100W GaN Charger",
        category="Accessories",
        subcategory="Charger",
        brand="Voltix",
        description="Fast 100W USB-C GaN charger",
        price=5199.0,
        mrp=5499.0,
        discount_percent=5.5,
        stock_quantity=12,
        warranty_months=12,
        returnable=False,
        replacement_available=True,
        rating=4.6,
        review_count=8,
        weight_kg=0.27,
        color="Charcoal",
        status="active",
    ),
    Product(
        product_id="PROD-00095",
        sku="VOL-HEA-6858-FOR",
        product_name="Voltix Beat Air 700",
        category="Headphones",
        subcategory="Over-ear ANC",
        brand="Voltix",
        description="Over-ear active noise cancelling headphones",
        price=2499.0,
        mrp=3499.0,
        discount_percent=28.5,
        stock_quantity=45,
        warranty_months=12,
        returnable=True,
        replacement_available=True,
        rating=4.3,
        review_count=15,
        weight_kg=0.23,
        color="Forest Green",
        status="active",
    ),
    Product(
        product_id="PROD-00050",
        sku="NOV-LAP-9921-SLV",
        product_name="NovaBook Ultra 15",
        category="Laptops",
        subcategory="Ultrabook",
        brand="NovaBook",
        description="High performance lightweight laptop",
        price=85000.0,
        mrp=95000.0,
        discount_percent=10.5,
        stock_quantity=8,
        warranty_months=24,
        returnable=True,
        replacement_available=True,
        rating=4.8,
        review_count=32,
        weight_kg=1.45,
        color="Silver",
        status="active",
    ),
    Product(
        product_id="PROD-00035",
        sku="HEL-CAM-7110-MID",
        product_name="Helix Optic One Mini",
        category="Cameras",
        subcategory="Vlogging Camera",
        brand="Helix",
        description="Compact vlogging camera with 1080p 30fps video",
        price=18999.0,
        mrp=21999.0,
        discount_percent=13.6,
        stock_quantity=15,
        warranty_months=12,
        returnable=True,
        replacement_available=True,
        rating=4.5,
        review_count=18,
        weight_kg=0.53,
        color="Midnight Blue",
        status="active",
    ),
]

SAMPLE_ORDERS = [
    # Delivered order within window, under v1 (placed 2026-04-10, delivered 2026-04-15)
    Order(
        order_id="ORD-000001",
        customer_id="CUST-00001",
        order_date="2026-04-10 10:00:00",
        order_status="delivered",
        payment_method="credit_card",
        payment_status="paid",
        subtotal=2499.0,
        discount=0.0,
        shipping_fee=0.0,
        tax=449.82,
        total_amount=2948.82,
        shipping_address="Flat 273, Celestial Apartments, Noida",
        city="Noida",
        state="Uttar Pradesh",
        estimated_delivery_date="2026-04-14",
        actual_delivery_date="2026-04-15",
        tracking_number="SLN12345678",
        courier="SwiftLane",
        delivery_status="delivered",
        delivery_otp_verified=True,
        cancellation_status="none",
        refund_status="none",
    ),
    # Shipped order in transit (placed under v1)
    Order(
        order_id="ORD-000002",
        customer_id="CUST-00001",
        order_date="2026-05-20 12:00:00",
        order_status="shipped",
        payment_method="credit_card",
        payment_status="paid",
        subtotal=5199.0,
        discount=0.0,
        shipping_fee=0.0,
        tax=935.82,
        total_amount=6134.82,
        shipping_address="Flat 273, Celestial Apartments, Noida",
        city="Noida",
        state="Uttar Pradesh",
        estimated_delivery_date="2026-05-25",
        actual_delivery_date=None,
        tracking_number="BAX98765432",
        courier="BlueArrow Express",
        delivery_status="in_transit",
        delivery_otp_verified=False,
        cancellation_status="none",
        refund_status="none",
    ),
    # Placed unshipped order (cancellable)
    Order(
        order_id="ORD-000003",
        customer_id="CUST-00002",
        order_date="2026-06-15 14:00:00",
        order_status="placed",
        payment_method="upi",
        payment_status="pending",
        subtotal=2499.0,
        discount=0.0,
        shipping_fee=0.0,
        tax=449.82,
        total_amount=2948.82,
        shipping_address="12, Indiranagar 100ft Rd, Bengaluru",
        city="Bengaluru",
        state="Karnataka",
        estimated_delivery_date="2026-06-20",
        actual_delivery_date=None,
        tracking_number=None,
        courier=None,
        delivery_status="pending",
        delivery_otp_verified=False,
        cancellation_status="none",
        refund_status="none",
    ),
    # High-value delivered order under v2 (> 75,000 INR -> Requires Human Escalation)
    Order(
        order_id="ORD-000004",
        customer_id="CUST-00002",
        order_date="2026-06-10 11:00:00",
        order_status="delivered",
        payment_method="credit_card",
        payment_status="paid",
        subtotal=85000.0,
        discount=0.0,
        shipping_fee=0.0,
        tax=15300.0,
        total_amount=100300.0,
        shipping_address="12, Indiranagar 100ft Rd, Bengaluru",
        city="Bengaluru",
        state="Karnataka",
        estimated_delivery_date="2026-06-14",
        actual_delivery_date="2026-06-14",
        tracking_number="KVC55443322",
        courier="KaveriCargo",
        delivery_status="delivered",
        delivery_otp_verified=True,
        cancellation_status="none",
        refund_status="none",
    ),
]

SAMPLE_ORDER_ITEMS = [
    OrderItem(
        order_item_id="OI-000001",
        order_id="ORD-000001",
        product_id="PROD-00095",
        quantity=1,
        unit_price=2499.0,
        discount=0.0,
        final_price=2499.0,
        item_status="delivered",
        return_status="none",
        refund_amount=0.0,
    ),
    OrderItem(
        order_item_id="OI-000002",
        order_id="ORD-000002",
        product_id="PROD-00001",
        quantity=1,
        unit_price=5199.0,
        discount=0.0,
        final_price=5199.0,
        item_status="shipped",
        return_status="none",
        refund_amount=0.0,
    ),
    OrderItem(
        order_item_id="OI-000003",
        order_id="ORD-000003",
        product_id="PROD-00095",
        quantity=1,
        unit_price=2499.0,
        discount=0.0,
        final_price=2499.0,
        item_status="placed",
        return_status="none",
        refund_amount=0.0,
    ),
    OrderItem(
        order_item_id="OI-000004",
        order_id="ORD-000004",
        product_id="PROD-00050",
        quantity=1,
        unit_price=85000.0,
        discount=0.0,
        final_price=85000.0,
        item_status="delivered",
        return_status="none",
        refund_amount=0.0,
    ),
]


def seed(session) -> None:
    """Seed test fixtures into the provided session."""
    for c in SAMPLE_CUSTOMERS:
        session.merge(c)
    for p in SAMPLE_PRODUCTS:
        session.merge(p)
    for o in SAMPLE_ORDERS:
        session.merge(o)
    for oi in SAMPLE_ORDER_ITEMS:
        session.merge(oi)
    session.commit()

    try:
        from pathlib import Path
        from scripts.import_novamart import import_product_specs
        p_dir = Path("public/products")
        if p_dir.exists():
            import_product_specs(session, p_dir)
    except Exception:
        pass

    logger.info("Seeded NovaMart test fixtures.")
